"""empty message

Revision ID: 2e41ffaa2c55
Revises: a72c3271abf0
Create Date: 2021-08-11 20:27:54.474461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e41ffaa2c55"
down_revision = "a72c3271abf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("modified", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "modified")
    op.drop_column("user", "created")
    # ### end Alembic commands ###
