"""empty message

Revision ID: a72c3271abf0
Revises: c7ca808ee61a
Create Date: 2021-08-07 20:43:28.108811

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a72c3271abf0"
down_revision = "c7ca808ee61a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email_address_key_key", "email_address", type_="unique")
    op.create_foreign_key(None, "reset_password", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reset_password", type_="foreignkey")
    op.create_unique_constraint("email_address_key_key", "email_address", ["key"])
    # ### end Alembic commands ###
